EconomicManagementAPP/Controllers/AccountTypesController.cs
using EconomicManagementAPP.Models;
using Microsoft.AspNetCore.Mvc;

namespace EconomicManagementAPP.Controllers
{
    public class AccountTypesController : Controller
    {
        private readonly IRepositorieAccountTypes repositorieAccountTypes;
        private readonly IRepositorieUsers repositorieUsers;

        public AccountTypesController(IRepositorieAccountTypes repositorieAccountTypes, IRepositorieUsers repositorieUsers)
        {
            this.repositorieAccountTypes = repositorieAccountTypes;
            this.repositorieUsers = repositorieUsers;
        }

        // Creamos index para ejecutar la interfaz
        public async Task<IActionResult> Index()
        {
            var userId = repositorieUsers.GetUserId();
            var accountTypes = await repositorieAccountTypes.GetAccountsTypes(userId);
            return View(accountTypes);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(AccountTypes accountTypes)
        {
            if (!ModelState.IsValid)
            {
                return View(accountTypes);
            }

            accountTypes.UserId = repositorieUsers.GetUserId();
            accountTypes.OrderAccount = 1;
            

            // Validamos si ya existe antes de registrar
            var accountTypeExist =
               await repositorieAccountTypes.Exist(accountTypes.Name, accountTypes.UserId);

            if (accountTypeExist)
            {
                // AddModelError ya viene predefinido en .net
                // nameOf es el tipo del campo
                ModelState.AddModelError(nameof(accountTypes.Name),
                    $"The account {accountTypes.Name} already exist.");

                return View(accountTypes);
            }
            await repositorieAccountTypes.Create(accountTypes);
            // Redireccionamos a la lista
            return RedirectToAction("Index");
        }

        // Hace que la validacion se active automaticamente desde el front
        [HttpGet]
        public async Task<IActionResult> VerificaryAccountType(string Name)
        {
            var userId = repositorieUsers.GetUserId();
            var accountTypeExist = await repositorieAccountTypes.Exist(Name, userId);

            if (accountTypeExist)
            {
                // permite acciones directas entre front y back
                return Json($"The account {Name} already exist");
            }

            return Json(true);
        }

        //Actualizar
        [HttpGet]
        public async Task<ActionResult> Modify(int id)
        {
            var userId = repositorieUsers.GetUserId();
            //var accountTypeId = repositorieAccountTypes.getAccountTypeId();

            var accountType = await repositorieAccountTypes.GetAccountById(id, userId);

            if (accountType is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            return View(accountType);
        }
        [HttpPost]
        public async Task<ActionResult> Modify(AccountTypes accountTypes)
        {
            var userId = repositorieUsers.GetUserId();
            var accountType = await repositorieAccountTypes.GetAccountById(accountTypes.Id, userId);

            if (accountType is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            await repositorieAccountTypes.Modify(accountTypes);// el que llega
            return RedirectToAction("Index");
        }
        // Eliminar
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var userId = repositorieUsers.GetUserId();
            var account = await repositorieAccountTypes.GetAccountById(id, userId);

            if (account is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            return View(account);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteAccount(int id)
        {
            var userId = repositorieUsers.GetUserId();
            var account = await repositorieAccountTypes.GetAccountById(id, userId);

            if (account is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            await repositorieAccountTypes.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

EconomicManagementAPP/Controllers/AccountsController.cs
using EconomicManagementAPP.Models;
using EconomicManagementAPP.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace EconomicManagementAPP.Controllers
{
    public class AccountsController : Controller
    {
        private IRepositorieAccounts repositorieAccounts;
        private IRepositorieUsers repositorieUsers;
        private IRepositorieAccountTypes repositorieAccountTypes;

        public AccountsController(IRepositorieAccounts repositorieAccounts,
                                  IRepositorieUsers repositorieUsers,
                                  IRepositorieAccountTypes repositorieAccountTypes)
        {
            this.repositorieAccounts = repositorieAccounts;
            this.repositorieUsers = repositorieUsers;
            this.repositorieAccountTypes = repositorieAccountTypes;
        }

        public async Task<ActionResult> Index()
        {
            
            var accounts = await repositorieAccounts.GetAccounts();
            return View(accounts);
        }

        [HttpGet]
        public async Task<ActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(Accounts accounts)
        {
            if (!ModelState.IsValid)
            {
                return View(accounts);
            }

            accounts.AccountTypeId = 1;

            var accountsExist =
               await repositorieAccounts.Exist(accounts.Name, accounts.AccountTypeId);
            if (accountsExist)
            {
                ModelState.AddModelError(nameof(accounts.Name),
                    $"The account {accounts.Name} already exist.");
                return View(accounts);
            }
            await repositorieAccounts.Create(accounts);
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Modify(int Id)
        {

            var userId = repositorieUsers.GetUserId();

            var account = await repositorieAccounts.GetAccountById(Id, userId);
            if (account is null)
            {
                return RedirectToAction("NotFound", "Home");
            }
            return View(account);

        }

        [HttpPost]
        public async Task<ActionResult> Modify(Accounts accounts)
        {
            var userId = repositorieUsers.GetUserId();
            var account = await repositorieAccounts.GetAccountById(accounts.Id, userId);

            if (account is null)
            {
                return RedirectToAction("NotFound", "Home");
            }
            await repositorieAccounts.Modify(accounts);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int Id)
        {

            var userId = repositorieUsers.GetUserId();
            var account = await repositorieAccounts.GetAccountById(Id, userId);
            if (account is null)
            {
                return RedirectToAction("NotFound", "Home");
            }
            return View(account);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteAccount(int Id)
        {
            var userId = repositorieUsers.GetUserId();
            var account = await repositorieAccounts.GetAccountById(Id, userId);
            if (account is null)
            {
                return RedirectToAction("NotFound", "Home");
            }
            await repositorieAccounts.Delete(Id);
            return RedirectToAction("Index");
        }
    }
}

EconomicManagementAPP/Controllers/CategoriesController.cs
using EconomicManagementAPP.Models;
using Microsoft.AspNetCore.Mvc;

namespace EconomicManagementAPP.Controllers
{
    public class CategoriesController : Controller
    {

        private readonly IRepositorieCategories repositorieCategories;
        private readonly IRepositorieUsers repositorieUsers;

        public CategoriesController(IRepositorieUsers repositorieUsers, IRepositorieCategories repositorieCategories)
        {
            this.repositorieCategories = repositorieCategories;
            this.repositorieUsers = repositorieUsers;
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        public async Task<IActionResult> Index()
        {
            var userId = repositorieUsers.GetUserId();
            var categories = await repositorieCategories.GetCategories(userId);
            return View(categories);
        }


        [HttpPost]
        public async Task<IActionResult> Create(Categories categorie)
        {

            if (!ModelState.IsValid)
            {
                return View(categorie);
            }
            categorie.UserId = UsersController.valorSesion.Id;
            var categorieExist = await repositorieCategories.Exist(categorie.Name);
            if (categorieExist)
            {
                ModelState.AddModelError(nameof(categorie.Name),
                    $"User with email {categorie.Name} already exist.");
                return View(categorie);
            }
            var userId = repositorieUsers.GetUserId();
            categorie.UserId = userId;
            await repositorieCategories.Create(categorie);
            return RedirectToAction("Index");
        }

        //Actualizar
        public async Task<IActionResult> Modify(int id)
        {
            var userId = repositorieUsers.GetUserId();
            var categorie = await repositorieCategories.GetCategorieById(id, userId);

            if (categorie is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            return View(categorie);
        }

        [HttpPost]
        public async Task<IActionResult> Modify(Categories categorie)
        {

            if (!ModelState.IsValid)
            {
                return View(categorie);
            }

            var userId = repositorieUsers.GetUserId();
            var categorieDB = await repositorieCategories.GetCategorieById(categorie.Id, userId);

            if (categorieDB is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            categorie.UserId = userId;
            await repositorieCategories.Modify(categorie);
            return RedirectToAction("Index");
        }

        //Eliminar Categories
        public async Task<IActionResult> Delete(int id)
        {
            var userId = repositorieUsers.GetUserId();
            var categories = await repositorieCategories.GetCategorieById(id, userId);

            if (categories is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            return View(categories);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteCategorie(int id)
        {
            var userId = repositorieUsers.GetUserId();
            var categorie = await repositorieCategories.GetCategorieById(id, userId);

            if (categorie is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            await repositorieCategories.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

EconomicManagementAPP/Controllers/UsersController.cs
using EconomicManagementAPP.Models;
using Microsoft.AspNetCore.Mvc;

namespace EconomicManagementAPP.Controllers
{
    public class UsersController : Controller
    {

        private readonly IRepositorieUsers repositorieUser;

        internal static Users valorSesion;

        public UsersController(IRepositorieUsers repositorieUser)
        {
            this.repositorieUser = repositorieUser;
        }

        public async Task<IActionResult> Index()
        {
            var users = await repositorieUser.getUsers();
            return View(users);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel loginViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(loginViewModel);
            }

            var result = await repositorieUser.Login(loginViewModel.Email, loginViewModel.Password);

            if (result is null)
            {
                ModelState.AddModelError(String.Empty, "Wrong Email or Password");
                return View(loginViewModel);
            }
            else
            {
                valorSesion = result;
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Create(Users users)
        {
            if (!ModelState.IsValid)
            {
                return View(users);
            }
            var userExist = await repositorieUser.Exist(users.Email);
            if (userExist)
            {
                ModelState.AddModelError(nameof(users.Email),
                    $"User with email {users.Email} already exist.");
                return View(users);
            }
            if (users.Email == users.StandarEmail)
            {
                ModelState.AddModelError(nameof(users.Email),
                    $"User with email {users.Email} and {users.StandarEmail} are equals.");
                return View(users);
            }
            await repositorieUser.Create(users);
            return RedirectToAction("Login");
        }

        //Actualizar
        [HttpGet]
        public async Task<ActionResult> Modify(int id)
        {
            var user = await repositorieUser.getAccountById(id);

            if (user is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            return View(user);
        }

        [HttpPost]
        public async Task<ActionResult> Modify(Users users)
        {
            var user = await repositorieUser.getAccountById(users.Id);

            if (user is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            await repositorieUser.Modify(users);// el que llega
            return RedirectToAction("Index");
        }

        // Delete User
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var user = await repositorieUser.getAccountById(id);

            if (user is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            return View(user);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteUser(int id)
        {
            var user = await repositorieUser.getAccountById(id);

            if (user is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            await repositorieUser.Delete(id);
            return RedirectToAction("Index");
        }

        public IActionResult LogOut()
        {
            valorSesion = null;
            return RedirectToAction("Login");
        }
    }
}

EconomicManagementAPP/Views/Shared/_Layout.cshtml
@using EconomicManagementAPP.Controllers
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EconomicManagementAPP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EconomicManagementAPP.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between headerColor headerSize ">
                    <ul class="navbar-nav flex-grow-1">

                        @if (UsersController.valorSesion is not null)
                        {
                            <span class="leftHeader"></span>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users List</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="AccountTypes" asp-action="Index">Account Types</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Accounts" asp-action="Index">Accounts</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Transactions" asp-action="Index">Transactions</a>
                            </li>
                            <span class="leftHeader"></span>
                            <li class="nav-item">
                                <a class="size" asp-area="" asp-controller="Users" asp-action="LogOut"><img src="https://cdn-icons.flaticon.com/png/128/4034/premium/4034229.png?token=exp=1648943424~hmac=a4467b41031293b42d865a036bcd9383" /></a>
                            </li>
                        }
                        else
                        {
                            <span class="leftHeader"></span>
                            <li class="nav-item">
                                <a class="size" asp-area="" asp-controller="Users" asp-action="Create"><img src="https://cdn-icons-png.flaticon.com/128/1177/1177527.png" /></a>
                            </li>
                            <li class="nav-item">
                                <a class="size" asp-area="" asp-controller="Users" asp-action="Login"><img src="https://cdn-icons-png.flaticon.com/128/1177/1177568.png"/></a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-black footerSize headerColor">
        <span class="leftHeader"></span>
        <div class="sizeFooter">
            <img src="https://cdn-icons-png.flaticon.com/128/733/733547.png" />
            <img src="https://cdn-icons-png.flaticon.com/128/2111/2111463.png" />
            <img src="https://cdn-icons.flaticon.com/png/128/3670/premium/3670151.png?token=exp=1648780993~hmac=d98837437fda607295d4ac197b7c842d" />
            <img src="https://cdn-icons-png.flaticon.com/128/733/733585.png" />
        </div>
        <div class="container text-center">
            &copy; 2022 - EconomicManagementAPP <a asp-area="" asp-controller="Home" asp-action="Privacy"></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>